stages:
  - build

variables:
  # Kích hoạt BuildKit để build nhanh hơn và tối ưu cache
  DOCKER_BUILDKIT: 1

.docker-build-template:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

build-backend:
  extends: .docker-build-template
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/backend
  script:
    - cd backend
    - docker build --cache-from $IMAGE_NAME:stg-latest --build-arg BUILDKIT_INLINE_CACHE=1 -t $IMAGE_NAME:sha-$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:stg-latest .
    - docker push $IMAGE_NAME:sha-$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:stg-latest
    - |
      if [ -n "$DOKPLOY_BE_WEBHOOK_URL" ]; then
        echo "Triggering Backend Redeploy..."
        curl -sS -f -X POST "$DOKPLOY_BE_WEBHOOK_URL"
      else
        echo "DOKPLOY_BE_WEBHOOK_URL is not set. Skipping webhook."
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_PIPELINE_SOURCE == "web"'
      changes:
        - backend/**/*
        - .gitlab-ci.yml

build-frontend:
  extends: .docker-build-template
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/frontend
  script:
    - cd frontend
    - docker build --cache-from $IMAGE_NAME:stg-latest --build-arg BUILDKIT_INLINE_CACHE=1 -t $IMAGE_NAME:sha-$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:stg-latest .
    - docker push $IMAGE_NAME:sha-$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:stg-latest
    - |
      if [ -n "$DOKPLOY_FE_WEBHOOK_URL" ]; then
        echo "Triggering Frontend Redeploy..."
        curl -sS -f -X POST "$DOKPLOY_FE_WEBHOOK_URL"
      else
        echo "DOKPLOY_FE_WEBHOOK_URL is not set. Skipping webhook."
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_PIPELINE_SOURCE == "web"'
      changes:
        - frontend/**/*
        - .gitlab-ci.yml
